[build]
  command = "npm run build" # Replace this with your build command
  publish = "public"       # Replace this with the directory containing your build output

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
